### ISSUE TITLE
Include submodules in release tars.

### ISSUE THREAD

**Issue by clonex10100** [mihirlad55/polybar-dwm-module#19]
Right now the tar releases have have empty xpp and i3ipcpp directories. It would be great if you included the code so it's buildable from the tar. Thanks!

**Comment by mihirlad55** [comment]
Sorry for the late reply, I've been busy with school. Which tar releases are you referring to? There currently aren't any official tar releases for this module.

**Comment by mihirlad55** [comment]
I'm closing this issue since I haven't received a response. Feel free to create a new issue if you have any other questions.
