### ISSUE TITLE
libjsoncpp error after upgrading to fedora 33

### ISSUE THREAD

**Issue by ghost** [mihirlad55/polybar-dwm-module#20]
After upgrading to Fedora 33, launching polybar from the terminal returns a libjsoncpp error

Usually polybar would just launch after typing "polybar *bar name*" in the terminal, but after the upgrade it gives back this:

polybar: error while loading shared libraries: libjsoncpp.so.22: cannot open shared object file: No such file or directory

It was working fine before i upgraded

I don't think my config is to blame, but i append it
[config.txt](https://github.com/mihirlad55/polybar-dwm-module/files/5470222/config.txt)

WM: dwm 6.2
Distro: Fedora 33 Workstation

**Comment by mihirlad55** [comment]
This normally happens after updating jsoncpp. Try re-building polybar from scratch.

**Comment by ghost** [comment]
Ok, im gonna try

**Comment by ghost** [comment]
It went flawlessly, i don't know why yesterday the compiling process failed midway
Thank you

**Comment by ghost** [comment]
Should i close

**Comment by mihirlad55** [comment]
No problem, I will close the issue.
