### ISSUE TITLE
Update README to include the code of the example bar from the image

### ISSUE THREAD

**Issue by ViggoGaming** [mihirlad55/polybar-dwm-module#25]
## Why does polybar need this feature?

I think it is a quick implementation to just a the code used for the image inside of the README. It would be a great example for people to try out too.

## Describe the solution you'd like

I would like the solution to be that inside of the README there should be a snippet of the code from the image here [here](https://github.com/mihirlad55/polybar-dwm-module/blob/master/dwm-module.png)

**Comment by mihirlad55** [comment]
The screenshot in the README.md is a screenshot of my personal bar configuration. The main difference between shown configuration and my configuration is the colors. Anyway, I added a link to my configuration in the README as an additional example. See commit bb94e18
